export const MAX_PAGE_SIZE = 1000
export const DEFAULT_STREAM_PAGE_SIZE = 100
export const MAX_INDEX_ENTRIES_PER_RECORD = 32

export const MAX_KEY_BYTES = 512
export const MAX_VALUE_BYTES = 8 * 1024 * 1024
export const MAX_PROJECTOR_PAYLOAD_BYTES = MAX_VALUE_BYTES
export const MAX_SCAN_LIMIT = 1000
export const DEFAULT_SCAN_LIMIT = 100
export const DEFAULT_NAMESPACE = "default"
export const MAX_NAMESPACE_BYTES = 128

export const MAX_FORK_ID_BYTES = 128

export const MAX_ROLE_NAME_BYTES = 64

export const MAX_FRAME_BYTES = 64 * 1024 * 1024
export const MAX_QUERY_REPLY_BYTES = MAX_FRAME_BYTES

export const MAX_BATCH_OPS = 64

export const MAX_AGENT_STRING_BYTES = 256
export const MAX_IDEMPOTENCY_KEY_BYTES = 64
export const MAX_METADATA_ENTRIES = 32
export const MAX_METADATA_KEY_BYTES = 256
export const MAX_METADATA_VALUE_BYTES = 1024
export const MAX_METADATA_TOTAL_BYTES = 8192
export const MAX_BODY_REFERENCE_BYTES = 1024
export const MAX_CARD_CAPABILITIES = 64
export const MAX_CLIENT_METADATA = 64 * 1024

export const MAX_MEMORY_BODY_BYTES = MAX_VALUE_BYTES
export const MAX_RECALL_LIMIT = MAX_PAGE_SIZE

export const MAX_TEXT_QUERY_BYTES = 1024
export const DEFAULT_RECALL_LIMIT = DEFAULT_STREAM_PAGE_SIZE
export const MAX_MEMORY_TAGS = 16
export const MAX_MEMORY_TAG_BYTES = 64
export const MAX_GRAPH_NAME_BYTES = 128
export const MAX_GRAPH_TRAVERSE_DEPTH = 8
export const MAX_GRAPH_RESULT_ELEMENTS = 10_000
export const MAX_GRAPH_NODE_LABELS = 16
export const MAX_SOURCE_REF_BYTES = 2 * MAX_KEY_BYTES
