# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "A2aBridge",
    "Agdx",
    "AgdxStream",
    "AgentCtx",
    "AgentHandle",
    "AgentMessage",
    "BackendDescriptor",
    "BatchPublishRequest",
    "Capabilities",
    "CompiledSchema",
    "Cursor",
    "FileStore",
    "ForkHandle",
    "ForkPutRequest",
    "Graph",
    "InMemoryStore",
    "Kv",
    "KvDeleteManyRequest",
    "KvEntry",
    "KvPage",
    "KvScanRequest",
    "KvSetRequest",
    "Laser",
    "McpBridge",
    "Memory",
    "MemoryItem",
    "Message",
    "Provenance",
    "PublishRequest",
    "QueryRequest",
    "QueryResult",
    "Row",
    "Topics",
    "Workflow",
    "derive_conversation_id",
    "edge_id",
    "graph_edge",
    "graph_node",
    "new_conversation_id",
    "new_correlation_id",
    "node_id",
]

@typing.final
class A2aBridge:
    r"""
    An A2A bridge: drive an agent as an A2A task source (`message/send` ->
    `tasks/get` / `tasks/cancel`).
    """
    def submit(self, params: typing.Any) -> typing.Any:
        r"""
        `message/send`: publish the params (a dict, or raw JSON str / bytes) as a
        task and return the submitted task as a dict.
        """
    def task(self, id: builtins.str) -> typing.Any:
        r"""
        `tasks/get`: the task's current state (Working until an answer lands).
        """
    def cancel(self, id: builtins.str) -> typing.Any:
        r"""
        `tasks/cancel`: cancel the task and return it canceled.
        """
    def card(self) -> typing.Any:
        r"""
        The bridge's A2A Agent Card, for discovery.
        """

@typing.final
class Agdx:
    r"""
    The typed AGDX producer over one topic and conversation.
    """
    def command(self, correlation: builtins.str, body: typing.Any, *, operation: typing.Optional[builtins.str] = None, content_type: typing.Optional[builtins.str] = None, target: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Publish a `command` (expects a reply or effect under `correlation`).
        Returns the minted record id.
        """
    def respond(self, correlation: builtins.str, body: typing.Any, *, operation: typing.Optional[builtins.str] = None, content_type: typing.Optional[builtins.str] = None, target: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Publish a `response` (the paired answer to a command, same `correlation`).
        """
    def emit(self, body: typing.Any, *, operation: typing.Optional[builtins.str] = None, content_type: typing.Optional[builtins.str] = None, target: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Publish an `event` (expects nothing back).
        """
    def stream(self, correlation: builtins.str, purpose: builtins.str) -> AgdxStream:
        r"""
        Open a chunk-stream writer under `correlation`. `purpose` is the
        chunk-stream vocabulary ('chat', 'reasoning', or 'tool_args').
        """
    def request_input(self, reply_topic: builtins.str, prompt: typing.Any, *, timeout_secs: builtins.float = 30.0) -> typing.Any:
        r"""
        Human-in-the-loop interrupt/resume: publish a prompt `command` under a
        fresh correlation on this producer's topic, then await the human's
        correlated `response` on `reply_topic` up to `timeout_secs` and return
        its body bytes. A responder answers with `AgentCtx.respond_input`, or
        rejects with an error which raises here. Blocks the caller until the
        response lands or the timeout elapses, which is the point: the task is
        genuinely paused on a human.
        """

@typing.final
class AgdxStream:
    r"""
    A chunk-stream writer: `write` each chunk, then one terminal (`finish`). The
    opening chunk carries the purpose.
    """
    def write(self, body: typing.Any) -> typing.Any:
        r"""
        Publish the next chunk (str, bytes, or bytearray).
        """
    def finish(self, *, finish_reason: builtins.str = 'stop') -> typing.Any:
        r"""
        Publish the terminal chunk with the reason the stream ended (default 'stop').
        """

@typing.final
class AgentCtx:
    r"""
    The context handed to a Python handler: reply / send / request / spawn a
    sub-conversation, or reach the full `Laser` for everything else.
    """
    @property
    def message(self) -> AgentMessage:
        r"""
        The message currently being handled.
        """
    def laser(self) -> Laser:
        r"""
        The full client, for operations the ctx helpers do not cover (kv, query, ...).
        """
    def spawn_subconversation(self) -> Provenance:
        r"""
        A child conversation of the handled message, linked by parent / root ids.
        """
    def respond_input(self, reply_topic: builtins.str, response: typing.Any) -> typing.Any:
        r"""
        Resolve an AGDX request by publishing a correlated AGDX `response` on
        `reply_topic`, so the caller (a bridge `tasks/get` or tool result, or an
        `Agdx.request_input`) completes. Requires the handled message to be an AGDX
        envelope carrying a correlation, and the agent to have an id.
        """
    def respond(self, payload: typing.Any) -> typing.Any:
        r"""
        Reply on the agent's configured respond_on topic, chaining causality and
        routing back to the sender. Raises ConfigError if no respond_on was set.
        """
    def reply_on(self, topic: builtins.str, payload: typing.Any) -> typing.Any:
        r"""
        Reply on an explicit topic, chained off the handled message.
        """
    def send(self, topic: builtins.str, payload: typing.Any, provenance: Provenance) -> typing.Any:
        r"""
        Send to `topic` with an explicit provenance (no automatic causality).
        """
    def request(self, request_topic: builtins.str, reply_topic: builtins.str, payload: typing.Any, provenance: Provenance, *, timeout_secs: builtins.float = 30.0) -> typing.Any:
        r"""
        Send a request and await its correlated reply (see Laser.request).
        """

@typing.final
class AgentHandle:
    r"""
    Owns a spawned agent. Await `ready()` before publishing, `shutdown()` to stop
    and surface any consumer error, or `abort()` to stop immediately.
    """
    def ready(self) -> typing.Any:
        r"""
        Wait until the agent has joined its group and is polling.
        """
    def shutdown(self) -> typing.Any:
        r"""
        Signal the agent to stop, wait for it, and surface any consumer error.
        """
    def join(self) -> typing.Any:
        r"""
        Wait for the agent to finish (it runs until its consumer ends or errors).
        """
    def abort(self) -> None:
        r"""
        Abort the agent's task immediately, without waiting.
        """
    def __aenter__(self) -> typing.Any:
        r"""
        Enter `async with`: wait until the agent is ready, then yield the handle.
        """
    def __aexit__(self, _exc_type: typing.Any, _exc_value: typing.Any, _traceback: typing.Any) -> typing.Any:
        r"""
        Exit `async with`: stop the agent and surface any consumer error. Returns
        `False` so an exception in the body is not suppressed.
        """

@typing.final
class AgentMessage:
    r"""
    A message delivered to / received by an agent: decoded provenance, raw
    payload, log position, and the AGDX envelope when present.
    """
    @property
    def payload(self) -> builtins.list[builtins.int]: ...
    @property
    def message_id(self) -> builtins.str: ...
    @property
    def provenance(self) -> Provenance: ...
    @property
    def conversation_id(self) -> builtins.str: ...
    @property
    def agent(self) -> typing.Optional[builtins.str]: ...
    @property
    def idempotency_key(self) -> typing.Optional[builtins.str]: ...
    @property
    def envelope(self) -> typing.Any:
        r"""
        The decoded AGDX envelope as a dict, or `None` for a plain message.
        """
    @property
    def agdx_body(self) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        The decoded AGDX envelope's body bytes, or `None` for a plain message.
        Unlike `payload` (the raw CBOR envelope for an AGDX message), this is the
        inner body the producer sent.
        """
    def body(self) -> builtins.list[builtins.int]:
        r"""
        The task body regardless of message shape: the AGDX envelope body for a
        command or response (its payload is the encoded envelope), else the raw
        payload. A handler reached by a contract or workflow reads this.
        """
    def json(self) -> typing.Any:
        r"""
        Decode the payload as JSON into a Python value.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BackendDescriptor:
    r"""
    One materialization backend the connected server exposes: identity only, a
    stable `id` and an opaque engine `kind`, with optional advisory `label` and
    `version` and a set of opaque `capabilities` tags the backend declares about
    itself (e.g. "ingest", "query", a query-surface feature). A consumer routes
    only to an advertised `id` and matches the tags it understands.
    """
    @property
    def id(self) -> builtins.str: ...
    @property
    def kind(self) -> builtins.str: ...
    @property
    def label(self) -> typing.Optional[builtins.str]: ...
    @property
    def version(self) -> typing.Optional[builtins.str]: ...
    @property
    def capabilities(self) -> builtins.list[builtins.str]: ...
    def has_capability(self, tag: builtins.str) -> builtins.bool:
        r"""
        Whether the backend declared the opaque capability `tag`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class BatchPublishRequest:
    r"""
    Fluent builder for a batch publish, finished with `await .send()` returning
    the number of records sent.
    """
    def inline_payload(self) -> BatchPublishRequest:
        r"""
        Inline the payload bytes for every record in the batch.
        """
    def projection_ref(self, value: builtins.str) -> BatchPublishRequest:
        r"""
        Stamp the projection ref on every record.
        """
    def schema_id(self, value: builtins.int) -> BatchPublishRequest:
        r"""
        Stamp a writer-schema id on every record.
        """
    def index(self, key: builtins.str, value: builtins.str) -> BatchPublishRequest:
        r"""
        Add an indexed field to every record in the batch.
        """
    def header(self, key: builtins.str, value: builtins.str) -> BatchPublishRequest:
        r"""
        Add a metadata header to every record in the batch.
        """
    def partition_key(self, key: builtins.str) -> BatchPublishRequest:
        r"""
        Pin every record in the batch to one partition by key.
        """
    def add_json(self, value: typing.Any) -> BatchPublishRequest:
        r"""
        Append one JSON-encoded record.
        """
    def add_msgpack(self, value: typing.Any) -> BatchPublishRequest:
        r"""
        Append one MessagePack-encoded record.
        """
    def add_payload(self, value: typing.Any) -> BatchPublishRequest:
        r"""
        Append one raw-bytes record.
        """
    def add_raw_bytes(self, value: typing.Any, content_type: builtins.str) -> BatchPublishRequest:
        r"""
        Append one already-encoded record plus its content type (e.g. "avro",
        "protobuf", "cbor"). Use it for bodies you encoded with another library.
        """
    def add_avro(self, schema: CompiledSchema, schema_id: builtins.int, value: typing.Any) -> BatchPublishRequest:
        r"""
        Append one record encoded as a raw Avro datum under a compiled writer
        schema, stamped with `agdx.ct=avro` + `agdx.sid`. The batch counterpart
        of `PublishRequest.avro`. Each record carries its own schema id, so a
        batch may mix writer schemas.
        """
    def extend_json(self, items: typing.Any) -> BatchPublishRequest:
        r"""
        Append every value in `items` as a JSON-encoded record.
        """
    def extend_msgpack(self, items: typing.Any) -> BatchPublishRequest:
        r"""
        Append every value in `items` as a MessagePack-encoded record.
        """
    def __len__(self) -> builtins.int:
        r"""
        Number of records queued so far.
        """
    def send(self) -> typing.Any:
        r"""
        Flush every queued record in a single Iggy send. Returns the count sent.
        """

@typing.final
class Capabilities:
    r"""
    A read-only snapshot of the premium capability set the connected
    infrastructure advertised. All flags are false against raw Apache Iggy.
    """
    @property
    def managed(self) -> builtins.bool:
        r"""
        Connected to a managed plane (the root managed switch).
        """
    @property
    def query(self) -> builtins.bool:
        r"""
        The managed query surface is served.
        """
    @property
    def query_consistency(self) -> builtins.str:
        r"""
        The strongest read-consistency the query surface serves
        (`eventual` / `read_your_writes` / `strong`).
        """
    @property
    def kv(self) -> builtins.bool:
        r"""
        The managed key-value surface is served.
        """
    @property
    def kv_cas(self) -> builtins.bool:
        r"""
        The key-value store serves compare-and-swap.
        """
    @property
    def kv_cas_fenced(self) -> builtins.bool:
        r"""
        The key-value store serves fenced compare-and-swap (the monotonic fence an
        exclusive workflow step needs for an at-most-once effect).
        """
    @property
    def graph(self) -> builtins.bool:
        r"""
        The managed knowledge-graph surface is served.
        """
    @property
    def forks(self) -> builtins.bool:
        r"""
        Managed copy-on-write forks are served.
        """
    @property
    def a2a_gateway(self) -> builtins.bool:
        r"""
        A managed A2A gateway is available.
        """
    @property
    def sessions(self) -> builtins.bool:
        r"""
        Platform-native session lifecycle.
        """
    @property
    def durable_dedup(self) -> builtins.bool:
        r"""
        Platform-side durable deduplication.
        """
    @property
    def backends(self) -> builtins.list[BackendDescriptor]:
        r"""
        The materialization backends the connected server exposes (identity
        only). Empty against raw Apache Iggy and servers that advertise none.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CompiledSchema:
    r"""
    A compiled writer schema: parse a registered schema definition once
    client-side, then encode / validate / decode bodies against it. Mirrors the
    Rust `CompiledSchema`. Avro and Protobuf schemas decode their schema-first
    bodies. A JSON Schema validates the decoded payload of a self-describing
    codec.
    """
    @staticmethod
    def compile(source: typing.Any, *, id: builtins.int = 0, name: typing.Optional[builtins.str] = None, version: typing.Optional[builtins.int] = None) -> CompiledSchema:
        r"""
        Compile a schema from a source dict (the same shape `register_schema`
        takes: `{"kind":"avro","schema":...}`, `{"kind":"protobuf",...}`, or
        `{"kind":"json_schema","schema":...}`). `id` labels the definition for
        error messages and is otherwise unused client-side. Raises
        `InvalidError` when the definition does not parse.
        """
    def encode_avro(self, value: typing.Any) -> bytes:
        r"""
        Encode a Python value as a raw Avro datum (single-object encoding, no
        container header), exactly the bytes a producer stamps alongside
        `agdx.sid`. Avro schemas only: a Protobuf or JSON schema raises
        `InvalidError`. Encoding fails with `CodecError` when the value does not
        match the schema.
        """
    def validate(self, payload: typing.Any) -> builtins.bool:
        r"""
        Whether `payload` (`str`, `bytes`, or `bytearray`) decodes under this
        schema (Avro / Protobuf) or, for a JSON Schema, parses as JSON and
        passes validation. `False` means the record would fall back to
        header-only extraction.
        """
    def validate_value(self, value: typing.Any) -> builtins.bool:
        r"""
        Validate an already-decoded Python value against a JSON Schema. Avro and
        Protobuf schemas return `False`.
        """
    def decode(self, payload: typing.Any) -> typing.Any:
        r"""
        Decode `payload` under this schema into a Python value, the model the
        managed plane extracts indexed fields from. Raises `CodecError` when the
        payload does not decode.
        """

@typing.final
class Cursor:
    r"""
    A resumable reader over one topic.
    """
    @property
    def offsets(self) -> builtins.list[builtins.int]:
        r"""
        The next offset to read on each partition. Persist this to resume later.
        """
    def poll(self) -> typing.Any:
        r"""
        Drain everything appended since the last poll, advancing the cursor. Returns
        the new messages ordered by timestamp, or an empty list when caught up.
        """

@typing.final
class FileStore:
    r"""
    A file-backed `StateStore` rooted at one directory: each key is hex-encoded
    into a file name, so any key is safe and no path traversal is possible.
    Durable across restarts, suited to an on-box disk mounted onto a deployment.
    Same `get` / `set` / `delete` vocabulary as `Kv` and `InMemoryStore`.
    """
    def __new__(cls, root: builtins.str) -> FileStore: ...
    def get(self, key: builtins.str) -> typing.Any:
        r"""
        The value bytes at `key`, or `None` if absent.
        """
    def set(self, key: builtins.str, value: typing.Any) -> typing.Any:
        r"""
        Store `value` (`str`, `bytes`, or `bytearray`) at `key`.
        """
    def delete(self, key: builtins.str) -> typing.Any:
        r"""
        Remove `key`. A no-op if it was already absent.
        """

@typing.final
class ForkHandle:
    r"""
    A handle to one fork by id.
    """
    @property
    def fork_id(self) -> builtins.str: ...
    def create(self, *, severed: builtins.bool = False, parent: typing.Optional[builtins.str] = None, tables: typing.Optional[typing.Sequence[builtins.str]] = None) -> typing.Any:
        r"""
        Open this fork. `severed=True` freezes a snapshot at the trunk's current
        offsets. The default (continuous) keeps seeing new trunk appends. Narrow a
        severed snapshot with `tables`. Returns the fork's metadata dict.
        """
    def promote(self) -> typing.Any:
        r"""
        Promote this fork onto the trunk, then squash it. Returns rows applied.
        """
    def squash(self) -> typing.Any:
        r"""
        Squash this fork (discard speculative rows). Returns whether one existed.
        """
    def put_row(self, table: builtins.str, partition_id: builtins.int, offset: builtins.int) -> ForkPutRequest:
        r"""
        Start writing one speculative row at (table, partition_id, offset).
        """

@typing.final
class ForkPutRequest:
    r"""
    Fluent builder for one speculative fork row.
    """
    def projection(self, id: builtins.str, version: builtins.int) -> ForkPutRequest:
        r"""
        Set the projection id/version this speculative row belongs to.
        """
    def field(self, name: builtins.str, value: builtins.str) -> ForkPutRequest:
        r"""
        Add one indexed field (queries filter and order on these).
        """
    def metadata(self, name: builtins.str, value: builtins.str) -> ForkPutRequest:
        r"""
        Add one non-indexed metadata header.
        """
    def payload(self, value: typing.Any) -> ForkPutRequest:
        r"""
        Attach an opaque payload body (str, bytes, or bytearray).
        """
    def embedding(self, embedding: typing.Sequence[builtins.float]) -> ForkPutRequest:
        r"""
        Attach an embedding as a list of floats.
        """
    def tombstone(self) -> ForkPutRequest:
        r"""
        Mark this as a tombstone: hide the trunk row at this coordinate.
        """
    def send(self) -> typing.Any:
        r"""
        Write the speculative row.
        """

@typing.final
class Graph:
    r"""
    A handle to the knowledge-graph surface `name`, built with `laser.graph(name)`.
    `upsert` writes nodes and edges, `neighbors` reads a node's neighborhood, and
    `query` runs a multi-hop traversal. A managed feature: against raw Apache Iggy
    every call raises `UnsupportedError`.
    """
    def upsert(self, nodes: list, edges: list) -> typing.Any:
        r"""
        Write `nodes` and `edges` (lists of dicts from `graph_node` / `graph_edge`)
        into the graph. Idempotent on the content-addressed ids, so re-upserting the
        same entities is a no-op.
        """
    def neighbors(self, node: builtins.str, *, direction: builtins.str = 'out', edge_type: typing.Optional[builtins.str] = None, depth: builtins.int = 1, limit: builtins.int = 0, as_of: typing.Optional[builtins.int] = None) -> typing.Any:
        r"""
        Read `node`'s neighbors: the nodes reachable in `direction` over
        `edge_type` (any type when `None`), following the same hop `depth` times.
        Returns a `{"nodes": [...], "edges": [...]}` dict.
        """
    def query(self, *, start_ids: typing.Optional[typing.Sequence[builtins.str]] = None, match_label: typing.Optional[builtins.str] = None, nearest: typing.Optional[tuple[typing.Sequence[builtins.float], builtins.int]] = None, hops: typing.Optional[typing.Sequence[tuple[builtins.str, builtins.str]]] = None, returns: builtins.str = 'nodes', limit: builtins.int = 0, as_of: typing.Optional[builtins.int] = None) -> typing.Any:
        r"""
        Run a traversal. Start from explicit node `start_ids`, from every node
        whose label equals `match_label`, or from the `nearest` nodes to an
        embedding (a `(embedding, k)` pair). `hops` is a list of `(edge_type,
        direction)` tuples, one per step. `returns` is `"nodes"`, `"edges"`,
        `"triplets"`, or `"paths"`. `as_of` (epoch micros) follows only edges
        valid at that instant.
        Returns a `{"nodes": [...], "edges": [...], "paths": [...]}` dict.
        """

@typing.final
class InMemoryStore:
    r"""
    An in-memory `StateStore`: `get` / `set` / `delete` over a process-local map.
    Fast and self-contained, lost on restart. The same vocabulary as `Kv`, so a
    handler written against this drops onto the managed store unchanged. Values
    read back as `bytes`.
    """
    def __new__(cls) -> InMemoryStore: ...
    def get(self, key: builtins.str) -> typing.Any:
        r"""
        The value bytes at `key`, or `None` if absent.
        """
    def set(self, key: builtins.str, value: typing.Any) -> typing.Any:
        r"""
        Store `value` (`str`, `bytes`, or `bytearray`) at `key`.
        """
    def delete(self, key: builtins.str) -> typing.Any:
        r"""
        Remove `key`. A no-op if it was already absent.
        """

@typing.final
class Kv:
    r"""
    A namespace-scoped view of the managed key-value store.
    """
    @property
    def namespace(self) -> builtins.str: ...
    def get(self, key: typing.Any) -> typing.Any:
        r"""
        Fetch the raw value bytes at `key`, or `None` if absent or expired.
        """
    def get_entry(self, key: typing.Any) -> typing.Any:
        r"""
        Fetch the full entry (key, value, version, expiry) at `key`, or `None`.
        """
    def get_typed(self, key: typing.Any) -> typing.Any:
        r"""
        Fetch and JSON-decode the value at `key` into a Python value, or `None`.
        """
    def set(self, key: typing.Any) -> KvSetRequest:
        r"""
        Start a set. Supply a value (`json` / `msgpack` / `payload`), optional
        `ttl` / `expires_at` / `expect_*`, then `await .send()` (or `.commit()`
        for a compare-and-swap).
        """
    def delete(self, key: typing.Any) -> typing.Any:
        r"""
        Delete `key`. Returns `True` when a live entry was removed.
        """
    def exists(self, key: typing.Any) -> typing.Any:
        r"""
        Test presence and read metadata without the value. Returns
        `(version, expires_at_micros, size_bytes)` or `None` when absent.
        """
    def expire(self, key: typing.Any, ttl_secs: typing.Optional[builtins.float] = None) -> typing.Any:
        r"""
        Set or refresh the entry's expiry in place. `ttl_secs` of `None` clears it.
        Returns the entry's (unchanged) version.
        """
    def patch(self, key: typing.Any, patch: typing.Any) -> typing.Any:
        r"""
        Apply a merge `patch` (bytes) to a structured value, returning the new
        version.
        """
    def lease(self, key: typing.Any, ttl_secs: builtins.float) -> typing.Any:
        r"""
        Acquire an advisory lease on `key` for `ttl_secs`. Returns
        `(lease_token, granted_ttl_secs)`.
        """
    def release(self, key: typing.Any, token: builtins.int) -> typing.Any:
        r"""
        Release a held lease early, presenting its `token`. Returns `True` when a
        held lease was released.
        """
    def delete_many(self) -> KvDeleteManyRequest:
        r"""
        Start a filtered bulk delete over this namespace.
        """
    def scan(self) -> KvScanRequest:
        r"""
        Start a scan over this namespace.
        """

@typing.final
class KvDeleteManyRequest:
    r"""
    Fluent builder for a filtered bulk delete.
    """
    def prefix(self, prefix: typing.Any) -> KvDeleteManyRequest: ...
    def range(self, start: typing.Any, end: typing.Any) -> KvDeleteManyRequest: ...
    def key_contains(self, substring: builtins.str) -> KvDeleteManyRequest: ...
    def send(self) -> typing.Any:
        r"""
        Apply the bulk delete. Returns the number of entries removed.
        """

@typing.final
class KvEntry:
    r"""
    One stored entry: key, value, version, and optional expiry.
    """
    @property
    def key(self) -> builtins.list[builtins.int]: ...
    @property
    def value(self) -> builtins.list[builtins.int]: ...
    @property
    def version(self) -> builtins.int: ...
    @property
    def expires_at_micros(self) -> typing.Optional[builtins.int]: ...
    def key_str(self) -> typing.Optional[builtins.str]:
        r"""
        The key decoded as UTF-8, or `None` for a binary key.
        """
    def json(self) -> typing.Any:
        r"""
        Decode the value as JSON into a Python value.
        """

@typing.final
class KvPage:
    r"""
    A page of scanned entries plus the cursor to resume after the last one.
    """
    @property
    def entries(self) -> builtins.list[KvEntry]: ...
    @property
    def cursor(self) -> typing.Optional[builtins.list[builtins.int]]: ...
    def __len__(self) -> builtins.int: ...

@typing.final
class KvScanRequest:
    r"""
    Fluent builder for a KV scan.
    """
    def prefix(self, prefix: typing.Any) -> KvScanRequest: ...
    def range(self, start: typing.Any, end: typing.Any) -> KvScanRequest: ...
    def key_contains(self, substring: builtins.str) -> KvScanRequest: ...
    def limit(self, n: builtins.int) -> KvScanRequest: ...
    def cursor(self, cursor: typing.Any) -> KvScanRequest: ...
    def fetch(self) -> typing.Any:
        r"""
        Fetch one page (entries plus the cursor to continue).
        """
    def entries(self) -> typing.Any:
        r"""
        Walk every matching entry across pages.
        """

@typing.final
class KvSetRequest:
    r"""
    Fluent builder for a KV set / compare-and-swap.
    """
    def payload(self, value: typing.Any) -> KvSetRequest:
        r"""
        Store raw bytes (str, bytes, or bytearray).
        """
    def json(self, value: typing.Any) -> KvSetRequest:
        r"""
        JSON-encode and store the value.
        """
    def msgpack(self, value: typing.Any) -> KvSetRequest:
        r"""
        MessagePack-encode and store the value.
        """
    def ttl(self, seconds: builtins.float) -> KvSetRequest:
        r"""
        Expire the entry `seconds` from now.
        """
    def expires_at(self, epoch_micros: builtins.int) -> KvSetRequest:
        r"""
        Expire the entry at an absolute epoch-microseconds timestamp.
        """
    def expect_version(self, version: builtins.int) -> KvSetRequest:
        r"""
        Compare-and-swap precondition: apply only if the key holds `version`.
        """
    def expect_absent(self) -> KvSetRequest:
        r"""
        Compare-and-swap precondition: apply only if the key does not exist.
        """
    def send(self) -> typing.Any:
        r"""
        Apply an unconditional write.
        """
    def commit(self) -> typing.Any:
        r"""
        Apply a compare-and-swap (needs `expect_version` / `expect_absent`).
        Returns the entry's new version.
        """

@typing.final
class Laser:
    r"""
    The connected LaserData / Apache Iggy client. Cheap to clone: the connection
    and producer cache are shared internally, so one `Laser` serves any number of
    concurrent operations.
    """
    @property
    def stream(self) -> typing.Optional[builtins.str]:
        r"""
        This client's default data stream, or `None` for a connection-only handle.
        """
    @property
    def ops_stream(self) -> builtins.str:
        r"""
        The Iggy stream carrying this client's query / control ops surface.
        """
    @property
    def control_topic(self) -> builtins.str:
        r"""
        The control-command topic on the ops stream.
        """
    def agdx(self, topic: builtins.str, source: builtins.str, conversation_id: builtins.str) -> Agdx:
        r"""
        A typed Agent Data Exchange Protocol producer publishing as `source`
        within `conversation_id` on `topic`. Every send is a validated AGDX
        envelope (`command` / `respond` / `emit` / `stream`).
        """
    def bootstrap(self, partitions: builtins.int) -> typing.Any:
        r"""
        Create the default data stream and the well-known agent topics, `partitions`
        each. Idempotent. Requires a default stream.
        """
    def send_agent(self, topic: builtins.str, payload: typing.Any, provenance: Provenance) -> typing.Any:
        r"""
        Append `payload` to an agent `topic`, stamping `provenance` as headers and
        keying the partition by conversation.
        """
    def request(self, request_topic: builtins.str, reply_topic: builtins.str, payload: typing.Any, provenance: Provenance, *, timeout_secs: builtins.float = 30.0) -> typing.Any:
        r"""
        Send a request and await its correlated reply on `reply_topic`, up to
        `timeout_secs`. Correlation is a fresh idempotency key the responder echoes.
        """
    def spawn_subconversation(self, parent: Provenance) -> Provenance:
        r"""
        A fresh child conversation of `parent`, carrying parent / root ids.
        """
    def redrive_dead_letter(self, capsule: typing.Any) -> typing.Any:
        r"""
        Redrive a dead-lettered message from a capsule dict (an AGDX dead-letter):
        re-read the original record and republish it verbatim so a fixed handler
        reprocesses it.
        """
    def spawn_agent(self, agent_id: builtins.str, listen_on: builtins.str, handler: typing.Any, *, respond_on: typing.Optional[builtins.str] = None, poll_interval_ms: typing.Optional[builtins.int] = None, warm_dedup: builtins.bool = False, dedup: typing.Optional[typing.Any] = None, capabilities: typing.Optional[typing.Sequence[builtins.str]] = None, ack_on_pickup: builtins.bool = False, health: typing.Optional[builtins.str] = None) -> AgentHandle:
        r"""
        Spawn an agent: join an Iggy consumer group named `agent_id` over
        `listen_on` and drive `handler` (an `async def handle(ctx, message)`) for
        each message, with at-least-once delivery, dedup, retry, and DLQ. Pass
        `dedup` (an `async def observe(key) -> bool`) for a custom, e.g. durable,
        deduplicator. Returns a handle to await readiness and stop it. Requires a
        default stream.
        """
    def contract(self, skill: builtins.str, payload: typing.Sequence[builtins.int], *, source: builtins.str, deadline_ms: builtins.int = 10000, fixed_inbox: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Send a directed task to one agent advertising `skill`, await its reply up to
        `deadline_ms`. Returns the reply body, or `None` if it did not complete in
        time. `fixed_inbox` routes to a fixed topic (a stock server with no presence
        command). Omit it to resolve each agent's advertised inbox.
        """
    def scatter(self, skill: builtins.str, payload: typing.Sequence[builtins.int], *, source: builtins.str, deadline_ms: builtins.int = 30000, fixed_inbox: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Scatter a directed task to every agent advertising `skill`, concurrently,
        and return the reply body of each that completed (a verifier or diagnostic
        panel). Unavailable and quarantined agents are excluded.
        """
    def quarantine(self, operator: builtins.str, agent: builtins.str) -> typing.Any:
        r"""
        Quarantine `agent` as `operator`: append the fact to the registry so every
        fused registry folds it and excludes the agent from routing.
        """
    def unquarantine(self, operator: builtins.str, agent: builtins.str) -> typing.Any:
        r"""
        Lift a prior quarantine on `agent` as `operator`: append the counterpart
        fact so every fused registry folds it and returns the agent to routing.
        """
    def workflow(self, name: builtins.str, *, fixed_inbox: typing.Optional[builtins.str] = None) -> Workflow:
        r"""
        Open a [`Workflow`](crate::workflow::PyWorkflow): dependency-ordered steps
        over the coordination primitives, with budgets, verifier panels, fenced
        exclusivity, on-timeout reassignment, and saga compensation. Declare steps,
        then `await wf.run()`. The name is the orchestrator identity the run
        dispatches as. `fixed_inbox` routes every step to a fixed topic (a stock
        server with no presence command); omit it to resolve advertised inboxes.
        """
    def assemble_context(self, conversation_id: builtins.str, *, topics: typing.Optional[typing.Sequence[builtins.str]] = None, last_n: typing.Optional[builtins.int] = None, roles: typing.Optional[typing.Sequence[builtins.str]] = None) -> typing.Any:
        r"""
        Replay a conversation's history off the log: read `topics` (default the
        command and response topics), order by timestamp, and apply a policy.
        `roles` keeps only messages from those agents. Otherwise the last
        `last_n` messages are kept (default 50). Returns the selected messages.
        """
    @staticmethod
    def connect(connection_string: builtins.str, *, stream: typing.Optional[builtins.str] = None, ops_stream: typing.Optional[builtins.str] = None, control_topic: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Connect using an Iggy connection string. The scheme is optional
        (`iggy://` is assumed). Pin a default `stream` so the convenience methods
        (`publish`, `bootstrap`, the agent verbs) take just a topic, otherwise
        name the stream per operation with the `*_on` methods.
        """
    def with_stream(self, stream: builtins.str) -> Laser:
        r"""
        A clone of this client pinned to a default data `stream`, sharing the one
        connection and producer cache. Re-scope a long-lived connection to as many
        streams as you like.
        """
    def with_ops_stream(self, ops_stream: builtins.str) -> Laser:
        r"""
        A clone whose query / control surface rides `ops_stream` instead of the
        default `_agdx`. Production keeps the default.
        """
    def with_control_topic(self, control_topic: builtins.str) -> Laser:
        r"""
        A clone whose control commands publish to `control_topic` on the ops
        stream instead of the default `control.commands`.
        """
    def capabilities(self) -> typing.Any:
        r"""
        The capability set this client negotiated with the connected infrastructure.
        """
    def ensure_topic(self, topic: builtins.str, partitions: builtins.int) -> typing.Any:
        r"""
        Idempotently create `topic` on the default stream with `partitions`,
        creating the stream first if needed. Requires a default stream.
        """
    def ensure_topic_on(self, stream: builtins.str, topic: builtins.str, partitions: builtins.int) -> typing.Any:
        r"""
        Idempotently create `topic` on an explicit `stream`.
        """
    def __repr__(self) -> builtins.str: ...
    def fork(self, fork_id: builtins.str) -> ForkHandle:
        r"""
        A handle to one fork (copy-on-write branch of the read model) by id.
        Forks are a managed feature: against raw Apache Iggy every operation
        raises `UnsupportedError`.
        """
    def forks(self) -> typing.Any:
        r"""
        Every open fork for the authenticated user, as a list of dicts.
        """
    def graph(self, name: builtins.str) -> Graph:
        r"""
        A handle to the knowledge-graph surface `name`. A managed feature: against
        raw Apache Iggy its calls raise `UnsupportedError`.
        """
    def register_graph(self, projection: typing.Any) -> typing.Any:
        r"""
        Register a graph projection from a dict (a projection with `kind = "graph"`
        and an `entity_schema`). It records the named knowledge graph and its
        node/edge extraction plan. Graph data is written via `graph(name).upsert(..)`,
        or by the projector when the projection is bound to a source topic, which
        applies the entity schema to each record. Applied asynchronously.
        """
    def drop_graph(self, id: builtins.str) -> typing.Any:
        r"""
        Drop the graph projection registered under `id`. Materialized nodes and
        edges are left untouched.
        """
    def a2a_bridge(self, source: builtins.str, request_topic: builtins.str, reply_topic: builtins.str) -> A2aBridge:
        r"""
        An A2A bridge mapping JSON-RPC methods onto agent topics, publishing as
        `source`. Use it to drive an agent as an A2A task source from Python.
        """
    def mcp_bridge(self, source: builtins.str, tool_topic: builtins.str, reply_topic: builtins.str, server_name: builtins.str, *, tools: typing.Optional[typing.Any] = None, resources: typing.Optional[typing.Any] = None, prompts: typing.Optional[typing.Any] = None, timeout_secs: typing.Optional[builtins.float] = None) -> McpBridge:
        r"""
        An MCP bridge serving tools / resources / prompts over the log, publishing
        tool calls as `source`. `tools` / `resources` / `prompts` are lists of
        dicts (a tool is `{name, description?, input_schema}`, a prompt is
        `{prompt: {name, title?, description?, arguments?}, messages: [[role, text]]}`).
        """
    def publish_state_snapshot(self, topic: builtins.str, source: builtins.str, conversation_id: builtins.str, state: typing.Any) -> typing.Any:
        r"""
        Publish an AG-UI state snapshot (the full shared state as JSON) on `topic`.
        """
    def publish_state_delta(self, topic: builtins.str, source: builtins.str, conversation_id: builtins.str, patch: typing.Any) -> typing.Any:
        r"""
        Publish an AG-UI state delta (an RFC 6902 JSON Patch document) on `topic`.
        """
    def reconstruct_state(self, conversation_id: builtins.str, topic: builtins.str) -> typing.Any:
        r"""
        Reconstruct AG-UI shared state by replaying the conversation's snapshot
        and deltas on `topic`, or `None` until a snapshot exists.
        """
    def agui_events(self, conversation_id: builtins.str, topic: builtins.str) -> typing.Any:
        r"""
        Render a conversation on `topic` as AG-UI events by reading the log.
        """
    def kv(self, namespace: builtins.str) -> Kv:
        r"""
        A handle to the managed key-value store scoped to `namespace`. Keys are
        `str` (UTF-8) or `bytes`. KV is a managed feature: against raw Apache Iggy
        every operation raises `UnsupportedError`.
        """
    def kv_namespaces(self) -> typing.Any:
        r"""
        Every KV namespace holding at least one entry for this caller.
        """
    def memory(self) -> Memory:
        r"""
        Log-backed memory over the durable agent audit log: `remember` appends,
        `forget` appends a tombstone, `recall` folds the log (most recent first,
        `semantic` ignored). The log is the source of truth, so this works on raw
        Apache Iggy. The returned handle holds its incremental recall cursor, so
        reuse it: each `recall` folds only what was appended since the last one.
        """
    def vector_memory(self, embedder: typing.Any) -> Memory:
        r"""
        In-process semantic memory: `embedder` is an `async def embed(text) ->
        list[float]`. `recall` with `semantic` ranks items by cosine similarity to
        the query embedding. Self-contained, so it works anywhere.
        """
    def query_memory(self, embedder: typing.Any, topic: builtins.str) -> Memory:
        r"""
        Managed semantic memory backed by the query index on `topic`, embedding
        with `embedder` (an `async def embed(text) -> list[float]`). A managed
        feature: against raw Apache Iggy it raises `UnsupportedError`.
        """
    def kv_memory(self, namespace: builtins.str, *, ttl_secs: typing.Optional[builtins.float] = None) -> Memory:
        r"""
        Managed memory backed by the key-value store in `namespace`, one entry per
        item, optionally expiring `ttl_secs` after each write. `recall` returns the
        most recent (`semantic` ignored), `forget` truly deletes. A managed
        feature: against raw Apache Iggy it raises `UnsupportedError`.
        """
    def publish(self, topic: builtins.str, *, stream: typing.Optional[builtins.str] = None) -> PublishRequest:
        r"""
        Start publishing a single record to `topic`. Chain `.index(..)`,
        `.json(..)` / `.msgpack(..)` / `.payload(..)`, then `await .send()`. Pass
        `stream=` to target an explicit stream instead of the default one.
        """
    def publish_batch(self, topic: builtins.str, *, stream: typing.Optional[builtins.str] = None) -> BatchPublishRequest:
        r"""
        Start a batch publish that flushes 1..N records in a single Iggy send.
        """
    def query(self, index: builtins.str) -> QueryRequest:
        r"""
        Start a query over the materialized `index`. Chain filters / sorts /
        aggregates, then `await` a terminal (`fetch`, `fetch_all`, `fetch_typed`,
        `fetch_one`). Query is a managed feature: against raw Apache Iggy it raises
        `UnsupportedError`.
        """
    def register_projection(self, projection: typing.Any) -> typing.Any:
        r"""
        Register a projection from a Python dict matching the projection schema.
        Applied asynchronously by the managed host (202-accepted): poll
        `get_projection(id)` to observe the apply.
        """
    def drop_projection(self, id: builtins.str) -> typing.Any:
        r"""
        Drop a projection by id. The managed host stops applying it. Existing rows stay.
        """
    def get_projection(self, id: builtins.str) -> typing.Any:
        r"""
        Read one projection's details by id, or `None` when no projection has it.
        """
    def list_projections(self, *, topic: typing.Optional[builtins.str] = None, name_contains: typing.Optional[builtins.str] = None, id_prefix: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        List projections, optionally narrowed by topic / name substring / id prefix.
        """
    def apply_binding(self, binding: typing.Any) -> typing.Any:
        r"""
        Apply a projection binding from a dict, routing a (stream, topic) source
        into registered projections.
        """
    def remove_binding(self, source: typing.Any, *, projection_ref: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Remove a binding for `source` (a {"stream","topic"} dict), optionally
        scoped to one `projection_ref`.
        """
    def register_schema(self, source: typing.Any, *, name: typing.Optional[builtins.str] = None, version: typing.Optional[builtins.int] = None) -> typing.Any:
        r"""
        Register a writer schema (Avro / Protobuf) from a source dict. Synchronous:
        returns the managed-allocated schema id.
        """
    def drop_schema(self, id: builtins.int) -> typing.Any:
        r"""
        Drop the writer schema at `id` (tombstone: existing records keep decoding).
        """
    def get_schema(self, id: builtins.int) -> typing.Any:
        r"""
        Read the writer schema at `id`, or `None` when the id is free.
        """
    def list_schemas(self) -> typing.Any:
        r"""
        List every known writer schema (active and tombstoned).
        """
    def reader(self, topic: builtins.str, *, stream: typing.Optional[builtins.str] = None, batch: typing.Optional[builtins.int] = None, from_offsets: typing.Optional[typing.Sequence[builtins.int]] = None) -> Cursor:
        r"""
        A resumable, offset-addressable reader over `topic`. Each `poll()` drains
        everything appended since the last poll across every partition, ordered by
        timestamp. You own the offsets: read them with `offsets`, persist them, and
        pass them back as `from_offsets=` to resume. Reads the default stream unless
        `stream=` names another.
        """

@typing.final
class McpBridge:
    r"""
    An MCP bridge: serve tools / resources / prompts over the log and route
    `tools/call` to an agent.
    """
    def initialize(self, protocol_version: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        `initialize`: the protocol version and advertised capabilities.
        """
    def list_tools(self) -> typing.Any:
        r"""
        `tools/list`.
        """
    def list_resources(self) -> typing.Any:
        r"""
        `resources/list`.
        """
    def read_resource(self, uri: builtins.str) -> typing.Any:
        r"""
        `resources/read`: the contents advertised for `uri`.
        """
    def list_prompts(self) -> typing.Any:
        r"""
        `prompts/list`.
        """
    def get_prompt(self, name: builtins.str) -> typing.Any:
        r"""
        `prompts/get`: the rendered messages for the prompt `name`.
        """
    def call_tool(self, name: builtins.str, arguments: typing.Any) -> typing.Any:
        r"""
        `tools/call`: route the call to the agent and return the tool result as a
        dict. `arguments` is a dict, or raw JSON str / bytes.
        """

@typing.final
class Memory:
    r"""
    Agent memory: `remember` a payload, `recall` the most relevant items, and
    `forget` one by id. The backend decides how recall ranks: the vector backend
    scores by semantic similarity to a query, the log and managed backends return
    the most recent. Scope every call to an agent and/or a conversation. Construct
    one from a `Laser` (`laser.memory()`, `laser.vector_memory(embedder)`,
    `laser.query_memory(...)`, `laser.kv_memory(...)`).
    """
    def remember(self, payload: typing.Any, *, agent: typing.Optional[builtins.str] = None, conversation: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Remember `payload` (`str`, `bytes`, or `bytearray`) under the given scope.
        Returns the new item's id (a time-ordered ULID string).
        """
    def recall(self, *, limit: builtins.int = 50, agent: typing.Optional[builtins.str] = None, conversation: typing.Optional[builtins.str] = None, semantic: typing.Optional[builtins.str] = None, strategy: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Recall up to `limit` items under the scope. Pass `semantic` text to rank by
        similarity (the vector backend embeds and scores it, the others ignore it
        and return the most recent).
        """
    def improve(self, memory_id: builtins.str, weight: builtins.float, *, agent: typing.Optional[builtins.str] = None, conversation: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Record feedback on a recalled item, the signal a ranking backend folds
        into future recall. `weight` is positive to promote, negative to demote.
        Returns the feedback record's id.
        """
    def forget(self, memory_id: builtins.str, *, agent: typing.Optional[builtins.str] = None, conversation: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Forget the item with id `memory_id` (a ULID string) under the scope.
        """

@typing.final
class MemoryItem:
    r"""
    One remembered item: its id, the raw payload bytes, and the provenance it was
    stored under (its scope's agent and conversation).
    """
    @property
    def id(self) -> builtins.str: ...
    @property
    def payload(self) -> builtins.list[builtins.int]: ...
    @property
    def text(self) -> builtins.str:
        r"""
        The payload decoded from UTF-8, raising if it is not valid text.
        """
    @property
    def provenance(self) -> Provenance: ...
    @property
    def conversation_id(self) -> builtins.str: ...
    @property
    def kind(self) -> builtins.str:
        r"""
        What the item is, as a string (`fact` / `message` / `summary` / `entity`
        / `feedback` / `procedure`).
        """
    @property
    def score(self) -> typing.Optional[builtins.float]:
        r"""
        The recall score from a ranking strategy, or `None` for an unranked recall.
        """
    def json(self) -> typing.Any:
        r"""
        Decode the payload as JSON into a Python value.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Message:
    r"""
    One log record: raw payload, log position, and string user headers.
    """
    @property
    def payload(self) -> builtins.list[builtins.int]: ...
    @property
    def message_id(self) -> builtins.str: ...
    @property
    def headers(self) -> builtins.dict[builtins.str, builtins.str]: ...
    def json(self) -> typing.Any:
        r"""
        Decode the payload as JSON into a Python value.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Provenance:
    r"""
    The agentic message spine: conversation, causality, routing, usage. Stamped on
    every agent message as headers.
    """
    @property
    def conversation_id(self) -> builtins.str: ...
    @property
    def parent_conversation_id(self) -> typing.Optional[builtins.str]: ...
    @property
    def root_conversation_id(self) -> typing.Optional[builtins.str]: ...
    @property
    def causal_parent(self) -> typing.Optional[builtins.str]: ...
    @property
    def agent(self) -> typing.Optional[builtins.str]: ...
    @property
    def target_agent_id(self) -> typing.Optional[builtins.str]: ...
    @property
    def idempotency_key(self) -> typing.Optional[builtins.str]: ...
    @property
    def input_tokens(self) -> typing.Optional[builtins.int]: ...
    @property
    def output_tokens(self) -> typing.Optional[builtins.int]: ...
    @property
    def cost_usd(self) -> typing.Optional[builtins.float]: ...
    def __new__(cls, *, conversation_id: typing.Optional[builtins.str] = None, causal_parent: typing.Optional[builtins.str] = None, parent_conversation_id: typing.Optional[builtins.str] = None, root_conversation_id: typing.Optional[builtins.str] = None, agent: typing.Optional[builtins.str] = None, target_agent_id: typing.Optional[builtins.str] = None, idempotency_key: typing.Optional[builtins.str] = None, deadline_micros: typing.Optional[builtins.int] = None, input_tokens: typing.Optional[builtins.int] = None, output_tokens: typing.Optional[builtins.int] = None, cost_usd: typing.Optional[builtins.float] = None) -> Provenance: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class PublishRequest:
    r"""
    Fluent builder for a single-record publish, finished with `await .send()`.
    """
    def index(self, key: builtins.str, value: builtins.str) -> PublishRequest:
        r"""
        Index `value` under `agdx.idx.<key>` so queries can match / sort on it.
        A record with zero indexed fields is dropped by the projector.
        """
    def header(self, key: builtins.str, value: builtins.str) -> PublishRequest:
        r"""
        Attach a non-indexed metadata header, surfaced as `Row.metadata`.
        """
    def inline_payload(self) -> PublishRequest:
        r"""
        Inline the payload bytes alongside the indexed row so readers can fetch
        the body back through the query layer. Off by default.
        """
    def projection_ref(self, value: builtins.str) -> PublishRequest:
        r"""
        Route the record through a projection by ref (e.g. "order.v1").
        """
    def schema_id(self, value: builtins.int) -> PublishRequest:
        r"""
        Stamp a writer-schema id on `agdx.sid`.
        """
    def partition_key(self, key: builtins.str) -> PublishRequest:
        r"""
        Pin the record to a partition by key (preserves per-key order).
        """
    def json(self, value: typing.Any) -> PublishRequest:
        r"""
        Encode the body as JSON and stamp `agdx.ct=json`. Accepts any
        JSON-serializable Python value (dict, list, scalar).
        """
    def msgpack(self, value: typing.Any) -> PublishRequest:
        r"""
        Encode the body as MessagePack and stamp `agdx.ct=msgpack`.
        """
    def payload(self, value: typing.Any) -> PublishRequest:
        r"""
        Use raw payload bytes (str, bytes, or bytearray) with no content-type tag.
        """
    def raw_bytes(self, value: typing.Any, content_type: builtins.str) -> PublishRequest:
        r"""
        Use already-encoded raw bytes plus a content type (e.g. "avro",
        "protobuf", "cbor"). Encode the body with whichever library you prefer,
        hand the bytes and the codec tag in one call.
        """
    def avro(self, schema: CompiledSchema, schema_id: builtins.int, value: typing.Any) -> PublishRequest:
        r"""
        Encode `value` as a raw Avro datum under a compiled writer schema and
        stamp `agdx.ct=avro` + `agdx.sid`. Compile the schema once with
        `CompiledSchema.compile(..)` and reuse it. Encoding fails client-side
        (`CodecError`) when the value does not match the schema.
        """
    def send(self) -> typing.Any:
        r"""
        Publish the record.
        """

@typing.final
class QueryRequest:
    r"""
    Fluent query builder over a materialized index. Mutates an owned `Query` and
    executes it through the managed query command at a terminal.
    """
    def where_eq(self, field: builtins.str, value: builtins.str) -> QueryRequest:
        r"""
        Exact-match on an indexed field (point lookup).
        """
    def fork(self, fork_id: builtins.str) -> QueryRequest:
        r"""
        Resolve against a fork's copy-on-write view instead of the trunk.
        """
    def filter_eq(self, field: builtins.str, value: typing.Any) -> QueryRequest: ...
    def filter_ne(self, field: builtins.str, value: typing.Any) -> QueryRequest: ...
    def filter_gt(self, field: builtins.str, value: typing.Any) -> QueryRequest: ...
    def filter_gte(self, field: builtins.str, value: typing.Any) -> QueryRequest: ...
    def filter_lt(self, field: builtins.str, value: typing.Any) -> QueryRequest: ...
    def filter_lte(self, field: builtins.str, value: typing.Any) -> QueryRequest: ...
    def filter_in(self, field: builtins.str, values: typing.Any) -> QueryRequest: ...
    def filter_contains(self, field: builtins.str, value: builtins.str) -> QueryRequest: ...
    def filter_prefix(self, field: builtins.str, value: builtins.str) -> QueryRequest: ...
    def message_type(self, value: builtins.str) -> QueryRequest:
        r"""
        Filter on the indexed message type.
        """
    def time_range(self, start: builtins.int, end: builtins.int) -> QueryRequest:
        r"""
        Filter rows whose timestamp (epoch micros) falls in [start, end].
        """
    def order_asc(self, field: builtins.str) -> QueryRequest: ...
    def order_desc(self, field: builtins.str) -> QueryRequest: ...
    def limit(self, n: builtins.int) -> QueryRequest: ...
    def offset(self, n: builtins.int) -> QueryRequest: ...
    def with_payload(self) -> QueryRequest:
        r"""
        Return the opaque payload bytes on each row.
        """
    def select_fields(self, fields: typing.Sequence[builtins.str]) -> QueryRequest:
        r"""
        Project only the named indexed fields into each row.
        """
    def read_your_writes(self) -> QueryRequest:
        r"""
        Require read-your-writes consistency.
        """
    def consistency(self, level: builtins.str) -> QueryRequest:
        r"""
        Set the read-consistency level: 'eventual', 'read_your_writes', or 'strong'.
        """
    def distinct(self) -> QueryRequest:
        r"""
        Return only distinct rows over the projected fields (needs select_fields).
        """
    def count(self) -> QueryRequest: ...
    def sum(self, field: builtins.str) -> QueryRequest: ...
    def avg(self, field: builtins.str) -> QueryRequest: ...
    def min(self, field: builtins.str) -> QueryRequest: ...
    def max(self, field: builtins.str) -> QueryRequest: ...
    def count_distinct(self, field: builtins.str) -> QueryRequest: ...
    def stddev(self, field: builtins.str) -> QueryRequest: ...
    def percentile(self, field: builtins.str, fraction: builtins.float) -> QueryRequest: ...
    def group_by(self, fields: typing.Sequence[builtins.str]) -> QueryRequest:
        r"""
        Group the aggregate by the named fields.
        """
    def window(self, field: builtins.str, every_micros: builtins.int) -> QueryRequest:
        r"""
        Bucket the aggregate into tumbling windows of `every_micros` over `field`.
        """
    def raw_sql(self, sql: builtins.str) -> QueryRequest:
        r"""
        Raw-SQL escape hatch (single read-only SELECT, SQL backends only).
        """
    def nearest(self, embedding: typing.Sequence[builtins.float], top_k: builtins.int, *, field: typing.Optional[builtins.str] = None) -> QueryRequest:
        r"""
        Approximate nearest-neighbour search on `field` (default "embedding").
        """
    def fetch(self) -> typing.Any:
        r"""
        Run the query and return one page plus pagination metadata.
        """
    def fetch_all(self) -> typing.Any:
        r"""
        Run the query and return every matching row, auto-paginating internally.
        """
    def fetch_typed(self) -> typing.Any:
        r"""
        Run the query, decoding every row's JSON payload into a Python value.
        """
    def fetch_one(self) -> typing.Any:
        r"""
        Run the query capped at one row, decoding its JSON payload, or `None`.
        """
    def to_dict(self) -> typing.Any:
        r"""
        The raw query as a dict (debugging).
        """

@typing.final
class QueryResult:
    r"""
    A page of query rows plus pagination metadata.
    """
    @property
    def rows(self) -> builtins.list[Row]: ...
    @property
    def offset(self) -> builtins.int: ...
    @property
    def limit(self) -> builtins.int: ...
    @property
    def total(self) -> builtins.int: ...
    @property
    def has_more(self) -> builtins.bool: ...
    def __len__(self) -> builtins.int: ...

@typing.final
class Row:
    r"""
    One materialized query row: indexed fields, ride-along metadata, log position,
    optional inlined payload, and vector score.
    """
    @property
    def headers(self) -> builtins.dict[builtins.str, builtins.str]: ...
    @property
    def metadata(self) -> builtins.dict[builtins.str, builtins.str]: ...
    @property
    def partition(self) -> typing.Optional[builtins.int]: ...
    @property
    def offset(self) -> typing.Optional[builtins.int]: ...
    @property
    def payload(self) -> typing.Optional[builtins.list[builtins.int]]: ...
    @property
    def score(self) -> typing.Optional[builtins.float]: ...
    def json(self) -> typing.Any:
        r"""
        Decode the inlined payload as JSON into a Python value, or `None` when the
        row carries no payload.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Topics:
    r"""
    The well-known agent topic names, so callers reference `Topics.COMMANDS`
    instead of retyping the string. Any other name works too: the agent methods
    take a plain topic string.
    """
    COMMANDS: builtins.str = 'agent.commands'
    RESPONSES: builtins.str = 'agent.responses'
    TOOL_CALLS: builtins.str = 'agent.tool_calls'
    TOOL_RESULTS: builtins.str = 'agent.tool_results'
    LLM_IO: builtins.str = 'agent.llm_io'
    HUMAN_INPUT: builtins.str = 'agent.human_input'
    AUDIT: builtins.str = 'agent.audit'
    DLQ: builtins.str = 'agent.dlq'

@typing.final
class Workflow:
    r"""
    A journalled directed-acyclic workflow over the coordination primitives, the
    Python view of the Rust engine. Declare steps with [`step`](Self::step), set a
    [`budget`](Self::budget), then `await wf.run(source=...)`. Each step is a
    directed task to its target, ordered by its declared dependencies, with an
    optional verifier panel, exclusivity (a fenced at-most-once effect), an
    on-timeout policy, and a compensation (the saga rollback).
    """
    def budget(self, *, tokens: typing.Optional[builtins.int] = None, wall_clock_ms: typing.Optional[builtins.int] = None, invocations: typing.Optional[builtins.int] = None) -> None:
        r"""
        Cap the workflow's spend. Any dimension left `None` is unbounded. The token
        ceiling counts only the usage an AGDX reply carries, so it is advisory.
        """
    def step(self, label: builtins.str, *, build: typing.Any, to: typing.Optional[builtins.str] = None, to_capable: typing.Optional[builtins.str] = None, all_capable: typing.Optional[builtins.str] = None, after: typing.Optional[typing.Sequence[builtins.str]] = None, verify: typing.Optional[typing.Any] = None, exclusive: builtins.bool = False, on_timeout: builtins.str = 'fail', compensate: typing.Optional[typing.Any] = None) -> None:
        r"""
        Add a step. Exactly one target is required: `to` (a named agent),
        `to_capable` (one agent advertising a skill), or `all_capable` (scatter to
        every agent advertising a skill and fold the replies, a verifier panel).
        `build(outputs) -> bytes` forms the task from the prior outputs. `after`
        declares the dependencies that order the step. `verify(output) -> bool`
        gates completion. `exclusive` claims a fenced lease (needs the managed
        plane). `on_timeout` is `"fail"` (default) or `"reassign"` (re-acquire the
        lease, bumping the fence, and hand the task to a fresh holder; needs an
        exclusive step). `compensate(outputs) -> bytes` is the rollback run if a
        later step fails.
        """
    def run(self) -> typing.Any:
        r"""
        Run the workflow, returning the completed steps' outputs keyed by label.
        The workflow name is the orchestrator identity it dispatches as, so it must
        be a valid agent id. A failed step runs the compensations in reverse and
        raises.
        """

def derive_conversation_id(seed: builtins.str) -> builtins.str:
    r"""
    A stable conversation id derived from `seed` (the same seed always yields the
    same id), for per-seed ordering and isolation without coordination.
    """

def edge_id(from_id: builtins.str, edge_type: builtins.str, to_id: builtins.str) -> builtins.str:
    r"""
    The content-addressed id for the edge `edge_type` from `from_id` to `to_id`.
    """

def graph_edge(from_node: typing.Any, edge_type: builtins.str, to_node: typing.Any) -> typing.Any:
    r"""
    Build an edge dict of `edge_type` from `from_node` to `to_node` (both node
    dicts), its id content-addressed over the endpoints and type.
    """

def graph_node(label: builtins.str, value: builtins.str) -> typing.Any:
    r"""
    Build a node dict for the entity `value` labelled `label`: its id
    content-addressed and the value kept as a `value` attribute, so re-observing
    the same entity converges. The ergonomic way to assemble a node for `upsert`.
    """

def new_conversation_id() -> builtins.str: ...

def new_correlation_id() -> builtins.str: ...

def node_id(label: builtins.str, value: builtins.str) -> builtins.str:
    r"""
    The content-addressed id for the entity `value` labelled `label`, as a
    Crockford string. The same entity always yields the same id, in any SDK, so a
    graph shared across languages converges on one node.
    """


class LaserError(Exception):
    code: builtins.str
    retryable: builtins.bool
    unsupported: builtins.bool
    not_found: builtins.bool
    version_skew: builtins.bool
    version_conflict: builtins.bool
    stale: builtins.bool

class ConfigError(LaserError): ...
class TimeoutError(LaserError): ...
class QueryError(LaserError): ...
class KvError(LaserError): ...
class ForkError(LaserError): ...
class UnsupportedError(LaserError): ...
class InvalidError(LaserError): ...
class CodecError(LaserError): ...
class ProtocolError(LaserError): ...
class TransportError(LaserError): ...
