mod agdx;
mod agent;
mod agent_runtime;
mod blob;
mod chunks;
mod client;
mod context;
mod convert;
mod crash_context;
mod errors;
mod fork;
mod govern;
mod graph;
mod intent;
mod interop;
mod kv;
mod memory;
mod publish;
mod query;
mod rbac;
mod reader;
mod runs;
mod schema;
mod sign;
mod snapshot;
mod state_store;
mod stream;
mod swarm;
mod transport;
mod typed;
mod watch;
mod workflow;

use pyo3::prelude::*;
use pyo3::wrap_pyfunction;
use pyo3_stub_gen::define_stub_info_gatherer;

#[pymodule]
fn laser_sdk(py: Python<'_>, module: &Bound<'_, PyModule>) -> PyResult<()> {
    // Bridge Rust `log` records to Python's `logging`, so the runtime's
    // diagnostics land on the `laser_sdk` logger a host app already configures
    // instead of on stderr. Best effort: a second import must not fail the module.
    let _ = pyo3_log::try_init();
    errors::register(py, module)?;
    module.add_class::<client::PyLaser>()?;
    module.add_class::<client::PyCapabilities>()?;
    module.add_class::<client::PyBackendDescriptor>()?;
    module.add_class::<publish::PyPublish>()?;
    module.add_class::<publish::PyBatchPublish>()?;
    module.add_class::<schema::PyCompiledSchema>()?;
    module.add_class::<sign::PySigningKey>()?;
    module.add_class::<sign::PyKeyRegistry>()?;
    module.add_class::<query::PyQuery>()?;
    module.add_class::<query::PyRow>()?;
    module.add_class::<query::PyQueryResult>()?;
    module.add_class::<kv::PyKv>()?;
    module.add_class::<kv::PyKvEntry>()?;
    module.add_class::<kv::PyKvPage>()?;
    module.add_class::<stream::PyStream>()?;
    module.add_class::<stream::PyTopic>()?;
    module.add_class::<watch::PyWatchReader>()?;
    module.add_class::<watch::PyChangeRecord>()?;
    module.add_class::<kv::PyKvSet>()?;
    module.add_class::<kv::PyKvScan>()?;
    module.add_class::<kv::PyKvDeleteMany>()?;
    module.add_class::<fork::PyForkHandle>()?;
    module.add_class::<fork::PyForkPut>()?;
    module.add_class::<agent::PyProvenance>()?;
    module.add_class::<agent::PyAgentMessage>()?;
    module.add_class::<agent::PyTopics>()?;
    module.add_class::<agdx::PyAgdx>()?;
    module.add_class::<agdx::PyAgdxStream>()?;
    module.add_class::<agent_runtime::PyAgentCtx>()?;
    module.add_class::<agent_runtime::PyAgentHandle>()?;
    module.add_class::<workflow::PyWorkflow>()?;
    module.add_class::<runs::PyRuns>()?;
    module.add_class::<runs::PyRunInfo>()?;
    module.add_class::<runs::PyRunPage>()?;
    module.add_class::<runs::PyRunBudget>()?;
    module.add_class::<rbac::PyGrant>()?;
    module.add_class::<rbac::PyRole>()?;
    module.add_class::<rbac::PyWhoami>()?;
    module.add_class::<rbac::PyAuthzEvent>()?;
    module.add_class::<rbac::PyAuthzHistoryPage>()?;
    module.add_class::<reader::PyCursor>()?;
    module.add_class::<typed::PyTypedRecords>()?;
    module.add_class::<typed::PyTypedRecord>()?;
    module.add_class::<reader::PyMessage>()?;
    module.add_class::<transport::PyProducer>()?;
    module.add_class::<transport::PyConsumer>()?;
    module.add_class::<transport::PyConsumerMessage>()?;
    module.add_class::<chunks::PyChunkAssembler>()?;
    module.add_class::<snapshot::PySnapshotStore>()?;
    module.add_class::<govern::PyGovernedAction>()?;
    module.add_class::<govern::PyActionDecision>()?;
    module.add_class::<govern::PyPolicyEvidence>()?;
    module.add_class::<govern::PyQuorumPolicy>()?;
    module.add_class::<govern::PyQuorumGovernor>()?;
    module.add_class::<govern::PySwappableGovernor>()?;
    module.add_class::<swarm::PyAgentActivity>()?;
    module.add_class::<swarm::PySwarmActivity>()?;
    module.add_class::<crash_context::PyCrashContext>()?;
    module.add_class::<intent::PyIntentPolicy>()?;
    module.add_class::<intent::PyIntent>()?;
    module.add_class::<intent::PyVote>()?;
    module.add_class::<intent::PyDecision>()?;
    module.add_class::<context::PyContextScope>()?;
    module.add_class::<context::PyScopedMemory>()?;
    module.add_class::<memory::PyMemory>()?;
    module.add_class::<memory::PyMemoryItem>()?;
    module.add_class::<graph::PyGraph>()?;
    module.add_class::<state_store::PyInMemoryStore>()?;
    module.add_class::<state_store::PyFileStore>()?;
    module.add_class::<interop::PyA2aBridge>()?;
    module.add_class::<interop::PyMcpBridge>()?;
    module.add_function(wrap_pyfunction!(agent::new_conversation_id, module)?)?;
    module.add_function(wrap_pyfunction!(agent::new_correlation_id, module)?)?;
    module.add_function(wrap_pyfunction!(agent::derive_conversation_id, module)?)?;
    module.add_function(wrap_pyfunction!(interop::authorize_edge, module)?)?;
    module.add_function(wrap_pyfunction!(rbac::grants_allow, module)?)?;
    module.add_function(wrap_pyfunction!(rbac::delegated_allow, module)?)?;
    module.add_function(wrap_pyfunction!(graph::node_id, module)?)?;
    module.add_function(wrap_pyfunction!(graph::edge_id, module)?)?;
    module.add_function(wrap_pyfunction!(graph::graph_node, module)?)?;
    module.add_function(wrap_pyfunction!(graph::graph_edge, module)?)?;
    module.add_function(wrap_pyfunction!(intent::decide, module)?)?;
    module.add_function(wrap_pyfunction!(agent_runtime::agent_message, module)?)?;
    module.add_function(wrap_pyfunction!(agent_runtime::agent_ctx, module)?)?;
    Ok(())
}

define_stub_info_gatherer!(stub_info);
