export const INTERNAL_GOVERN = Symbol("laser.internal.govern")
export const INTERNAL_NATIVE_CONSUMER = Symbol("laser.internal.native-consumer")
export const INTERNAL_REPLY_HUB = Symbol("laser.internal.reply-hub")
export const INTERNAL_TRANSPORT = Symbol("laser.internal.transport")
export const INTERNAL_VERIFIER = Symbol("laser.internal.verifier")
export const INTERNAL_RETURN_DELIVERY = Symbol("laser.internal.return-delivery")
